# Generated by Django 2.2 on 2021-08-11 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20210801_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания действия справочника этой версии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='ident',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Идентификатор справочника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
